# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Beast
last_update: "Site last built: "
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 5
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
url: https://thebeast.me # the base hostname & protocol for your site
repository: https://github.com/jbampton/jbampton.github.io
twitter_username: johnbampton
github_username:  jbampton
feed:
  path: atom.xml
# Build settings
markdown: kramdown
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
